version: 2

before:
  hooks:
    - go mod tidy
    - npm ci
    - npm run build

builds:
  - id: amatled-linux
    binary: amatled
    main: ./cmd/amatled
    goos: [linux]
    goarch: [amd64]
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: amatled-archive
    builds: [amatled-linux]
    name_template: "amatled_{{.Version}}_{{.Os}}_{{.Arch}}"
    format: tar.gz

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  name_template: "v{{.Version}}"
  draft: false
  prerelease: auto
